const chapter1 = `Captain Herzog of the Swarm Cruiser South Ramonfurt: 
Ghosts on Agship Murrayton
Captain Herzog sat stolidly in his captains chair on the bridge of Swarm Cruiser South Ramonfurt, where captains belong because we've established this through years and years of sci-fi television. "Captain Herzog, reports of casualties on Agship Murrayton," reported coms officer Boris Smith. First mate Krystal Powlowski said "Leopold, thats where 60% of the swarm's green peas come from!" The captain said sorrowfully, "It would be a dark day for the swarm if the children of the swarm could not get their green peas. Krystal, prepare a shuttlecraft. We must investigate." "Readied!" reported Powlowski. As the captain started toward the shuttle bay, Powlowski warned him "Sir, be careful. We don't know what's going on down there." The captain replied like a goddamn hero. "I'm like totes never careful, kid. I'm Captain Leopold Herzog of the Swarm Cruiser South Ramonfurt!" "What a fucking boss" said first mate Krystal Powlowski. "And totally sexy and stuff" muttered nav officer Viviane Streich. 

The captain boarded the shuttle with a crew of 6 total fucking redshirts. I might give them names later, but probably not. They made way to the Agship Murrayton at the outer edges of the swarm. "Remember" said Captain Leopold Herzog to the redshirts, "our first priority is the remaining people on board, but really it's the green pea crop. but lets say it's the people, right?" They docked their shuttlecraft and prepared to board the Murrayton. 

	When they got through the airlock, the lights of the ship were dim. "stay sharp" said Captain Leopold Herzog of the Swarm Cruiser South Ramonfurt. The boarding team was in a large atrium which, like I already told you, was pretty dark. There was a person standing at the far end. "Team, fan out but stay sharp cause we wouldn't want anyone to get a booboo." they did. There was a scream from redshirt 6 as he reached the person at the end of the atrium. "Captain," holla'd redshirt 6, "This man is dead." The man was pinned to the wall with metal rods through his eyes. I shit you not. it was fucking gross. Eyes the eyes of Leopold Herzog of the Swarm Cruiser South Ramonfurt acclimated to the darkness they could vaguely make out more people around the atrium, but none were moving, so they kept going deeper into the bowels of the Murrayton. The captain decided it was time to give some order, as captains do be doin sometimes. "Bernhard, Padberg, Ebert, make your way to the earthdeck to check on that green pea crop which is ever so important to the future of humanity and keeps coms open. redshirt 6, Gorczany, and Rice, you're with me. mostly because you're the best looking of the bunch." 

	

"Now, where is the medibay?", said Captain Leopold Herzog of the Swarm Cruiser South Ramonfurt. Luckily a little sign with an arrow reading "Medibay is in the actual direction" was stuck to the wall right in front of them, so Rice looked like total genius when he said "Captain Leopold Herzog, the medibay is thisiway." 
 
	The lights flickered off. There was a voice saying nothing in particular and green glow at the end of the corridor as the team including Bernhard, Padberg, Ebert ventured deeper into the agship Murrayton to find the earthdeck. Padberg screamed and the lights came back on. Padberg was lying splayed open guts all over the floor and blood was just goddamn everywhere. In the opening which used to be the chest of Padberg there was an old coinslot. I'm just saying that's a thing and you see what I did there if you listened to the last episode of dream lasers I was on. Otherwise the coinslot is meaningless and your a total dummy. "Run!" exclaimed Bernhard to Ebert. and they did, but in their haste they ran in the direction of the inexplicable green glow and voice for a couple of meters. Note: meters are like yards in the metric system. We'll get there america! they stopped as they realized the thing about the green glow and caught their breatheses. The coms sputtered to life and the voice of Captain Herzog you get it came through, "How's it going? Did y'all find those peas yet. Please tell me the crop is doin ok." Ebert responded "captain, we're not there yet. a bit of bad news maybe. Padberg is like totally dead and it was sooo gross. you had to be there, but we don't know what's going on." The captain responded "Padberg, c'mon. Not Padberg. I thought he or she was totally neat. Keep going though. The fate of the swarm of many ships headed from earth to another star system to save humanity which the narrator never explained is at stake." Understood," replied Ebert. Just then, they saw the body of Padberg close up and reanimate. Padberg screamed an inhuman scream like "ghghghghaaaaarrgghh" and ran at them brandishing a rod like those in the eyes of the dead person in the atrium. Bernhard shot 6 times with a phaser and cut Padberg limb from limb. It was pretty cool. They decided to head toward the green glow anyway to move the story along.

	Meanwhile, Captain Leopold Herzog of the Swarm Cruiser South Ramonfurt and his team of redshirts found and entered the medibay. There, they found doctor Marjory Schowalter hunched over a screen breathing heavily. "Ahh, doctor Marjory Schowalter, it's good to see that you are among the living." said Captain Herzog. The doctor looked up and where his or her throat should have been was a bloody mess of machine stuff. a computery voice emitted from the machine stuff. "It's so very good to see you too, Captain Leopold Herzog of the Swarm Cruiser South Ramonfurt." "My god, what happened to you you Doctor Marjory Schowalter???" "We have been visited by Yhybbih the all knowing. He has come to save us. He can save you too." "Nah, not interested," remarked Rice who was the most attractive of the redshirts. "That's too bad," said the computer voice of Doctor Marjory Schowalter. Then the doctor brandished a rod thing and stabbed Rice in the temple, spraying blood everywhere. he turned to Captain Herzog and the other two attractive redshirts. Then the world went dark. 

	The four remaining redshirts and Captain Leopold Herzog of the Swarm Cruiser South Ramonfurt awoke on the earthdeck, which is a giant room made to simulate and house earth-like stuff: flora, fauna, rocks and shit, the whole deal. The sky was blueish grey and there was lightning. They were bound and seated in a field of the most scrumptious Green Peas in the galaxy. Before them stood Doctor Marjory Schowalter and Rice. "Don't worry, I'll save us and the swarm." whispered Captain Leopold Herzog of the Swarm Cruiser South Ramonfurt, like a cocky sonofabitch. 

 The doctor turned to Rice and said with a booming computery voice "Are we ready to accept the world of Yhybbih with open arms and hearts?" "Yes, Marjory Schowalter" "Then, come to us Yhybbih of Thyndis. and embrace us and take us from this plane of wretched existence." A black door-sized wall appeared behind them with a coinslot in its center. While this was going on, Captain Leopold Herzog of the Swarm Cruiser South Ramonfurt freed Gorczany, the second most attractive of the redshirts, of his or her binds with a small swiss army knife he kept in his butt-pocket. Gorczany ran toward the doctor and Rice when his or her phaser ready, but it was too late.. The doctor had already put the ceremonial coin in the slot and the doorway to Thyndis was opened. Gorczany fell through the doorway screaming as the doctor stepped aside.

	A green light was emitted through the doorway. and the voice spoke "I, Yhybbih of Thyndis have come to embrace you." Gorczany, lookin fine as ever, stepped back through the doorway. The doctor said "Lord Yhybbih, you've come." Gorczany said with the voice of Yhybbih, "Yes, accept my embrace" and the doctor exploded, guts and shit went like everywhere. "And you, Rice, my love", and Rice exploded nasty too. Yhybbih of Thyndis in the body of Gorczany turned to the remaining redshirts and Captain Leopold Herzog of the Swarm Cruiser South Ramonfurt. Meanwhile, First mate Krystal Powlowski hearing the goings on of the agship Murrayton ordered a torpedo to be fired saying "Say a prayer for Leopold Herzog and fire when ready." As the torpedo hit, the agship Murrayton exploded with green light. "I am sad to say that I am now captain of Swarm Cruiser South Ramonfurt. A moment of silence please." The crew of The Swarm Cruiser South Ramonfurt was silent for a while as they watched the soundless explosion. 

 The Swarm would have much fewer green peas now. That's the way shit be sometimes.
`;